server-ip: "strawberrysmp.falix.gg"

rules:
  - "No griefing or stealing."
  - "No cheating or hacked clients."
  - "No spam, flooding, or advertising."
  - "No NSFW content."
  - "No slurs or harassment."
  - "Do not impersonate staff or other players."
  - "Respect other players and staff."

spawn: {}
